config/routes.rb
Restaurant::Application.routes.draw do
  resources :reservations
  root 'reservations#index'
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  scope :by_table_id, ->(table_id) { where(table_id: table_id) }
  scope :overlapping, ->(start_time, end_time) { 
    where("start_time BETWEEN :start_time AND :end_time OR
             end_time BETWEEN :start_time AND :end_time OR
             (start_time < :start_time AND end_time > :end_time)",
             start_time: start_time, end_time: end_time)
  }
  scope :not_self_id, ->(id) { where.not(id: id) if id }

  validates :table_id, :start_time, :end_time, presence: true
  validates :table_id, numericality: {greater_than_or_equal_to: 1}

  validate :validate_times, :overbooking

  def overbooking
    if self.class.by_table_id(table_id).overlapping(start_time, end_time).not_self_id(id).any?
      errors.add(:base, "is already booked")
    end
  end

  def validate_times
    if end_time && start_time && end_time <= start_time
      errors.add(:base, "end_time must be after than start_time")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end


  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reservation }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:start_time, :end_time, :table_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.haml
= form_for @reservation do |f|
  - if @reservation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      %ul
        - @reservation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_time
    = f.text_field :start_time, class: 'datetimepicker'
  .field
    = f.label :end_time
    = f.text_field :end_time, class: 'datetimepicker'
  .field
    = f.label :table_id
    = f.number_field :table_id
  .actions
    = f.submit 'Save'

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table
  %tr
    %th Start time
    %th End time
    %th Table
    %th
    %th
    %th

  - @reservations.each do |reservation|
    %tr
      %td= reservation.start_time
      %td= reservation.end_time
      %td= reservation.table_id
      %td= link_to 'Show', reservation
      %td= link_to 'Edit', edit_reservation_path(reservation)
      %td= link_to 'Destroy', reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', reservations_path

app/views/reservations/show.html.haml
%p#notice= notice

%p
  %b Start time:
  = @reservation.start_time
%p
  %b End time:
  = @reservation.end_time
%p
  %b Table:
  = @reservation.table_id

= link_to 'Edit', edit_reservation_path(@reservation)
\|
= link_to 'Back', reservations_path